# Generated by Django 4.0.2 on 2022-02-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ties',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
