name: AWS SSM Send-Command Example

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: test
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.6.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Create env file
        run: |
          touch .env
          echo SECRET_KEY=eghszrdehrmhopdrtjdrherhesrth >> .env
          echo DB_NAME=player >> .env
          echo DB_USER=root >> .env
          echo DB_PASS= >> .env
          echo DB_HOST_2=127.0.0.1 >> .env
          echo DB_PORT=3306 >> .env

      - name: Run Tests
        run: |
          python manage.py test

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}
          comment: Deploy the master branch
          working-directory: /home/ubuntu/minigames
          command: /bin/sh ./deploy.sh
