name: AWS SSM Send-Command Example

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.6.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
      - name: Run Python commands
        run: |
          python -m pip install --upgrade pip
          ls -al
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python3 manage.py tests

      - uses: actions/checkout@v2
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}
          comment: Deploy the master branch
          working-directory: /home/ubuntu/minigames
          command: /bin/sh ./deploy.sh
