name: Deploy using AWS SSM Send-Command 

on:
    push:
        branches: [main]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
        instance-ids: ${{ secrets.INSTANCE_ID  }}
        comment: Deploy the main branch
        working-directory: /home/ubuntu/minigames
        command: /bin/sh ./deploy.sh